# Generated by Django 6.0.3 on 2026-04-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False, verbose_name="is verified"
            ),
        ),
    ]
